# Generated by Django 4.2.4 on 2023-09-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_resume_uploaddata_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('postdate', models.DateField()),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suser')),
            ],
        ),
    ]
